### ISSUE TITLE
vObject serailization error

### ISSUE THREAD

**Issue by gmtcrary** [osu-mist/dublabs-vcf-files#1]
This is the error I've been getting with the vObject library.

Traceback (most recent call last):
  File "locations_vcf_generator.py", line 78, in <module>
    print getDiningSerialization(x["attributes"])
  File "locations_vcf_generator.py", line 57, in getDiningSerialization
    return entry.serialize()
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/behavior.py", line 162, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/base.py", line 992, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/behavior.py", line 156, in serialize
    transformed = obj.transformFromNative()
  File "/home/takumi/.local/lib/python2.7/site-packages/vobject/base.py", line 226, in transformFromNative
    raise NativeError(msg, lineNumber)
vobject.base.NativeError: "In transformFromNative, unhandled exception on line None <type 'exceptions.AttributeError'>: 'unicode' object has no attribute 'family'"

**Comment by gmtcrary** [comment]
To install the vObject you have to run "pip install vobject"
